### PR TITLE
Encapsulate log streaming in a FileSink type

### LINKED ISSUE #350: synchronizeFile() is not supported on piped stdout
If you pipe `carthage build` into something else (or, say, run it from Xcode), the `--verbose` flag will cause the following crash:

> *** Terminating app due to uncaught exception 'NSFileHandleOperationException', reason: '*** -[_NSStdIOFileHandle synchronizeFile]: Operation not supported'

We shouldn't invoke [invoke `synchronizeFile()`](https://github.com/Carthage/Carthage/blob/26ea162f001f5333bcd5efcc73f7574705a5f46a/Source/carthage/Build.swift#L35) on an `stdout` handle.

### PR DESCRIPTION
**Pull request by jspahrsummers**
Resolves #350.

**To do:**

 - [x] Unit tests for `FileSink`

### CODE REVIEW

File: Source/carthage/Build.swift [hunk 1]
```diff
@@ -25,15 +25,14 @@ public struct BuildCommand: CommandType {
...
+			.map { (stdoutSink, temporaryURL) -> ColdSignal<()> in
 				let directoryURL = NSURL.fileURLWithPath(options.directoryPath, isDirectory: true)!
 
 				let (stdoutSignal, schemeSignals) = self.buildProjectInDirectoryURL(directoryURL, options: options)
-				stdoutSignal.observe { data in
-					stdoutHandle.writeData(data)
-					stdoutHandle.synchronizeFile()
-				}
+				stdoutSignal
+					.map { .Next(Box($0)) }
```
Comment (jspahrsummers) [inline Source/carthage/Build.swift]: This is a temporary hack. Once we're using the latest version of RAC, everything will be `Event`s, so we can hook up the standard output signal directly to the sink.

**Comment by jspahrsummers** [comment]
Ready for review.

File: Source/CarthageKit/FileSink.swift [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+	/// Upon a terminating event, the file will be flushed, and closed if
+	/// appropriate.
+	public func put(event: Event<NSData>) {
+		if let filePointer = filePointer {
+			switch event {
+			case let .Next(data):
+				fwrite(data.unbox.bytes, UInt(data.unbox.length), 1, filePointer)
+
+			case let .Error(error):
+				fputs(error.description + "\n", filePointer)
```
Comment (robrix) [inline Source/CarthageKit/FileSink.swift]: I’m a little surprised that this is writing the errors out as well; I had expected it would resurface them in another signal so you could e.g. maintain the stdout/stderr divide. Do you think that would be appropriate for the type?

File: Source/carthage/Build.swift [hunk 3]
```diff
@@ -93,33 +92,15 @@ public struct BuildCommand: CommandType {
...
-			}
-
-			let temporaryPath = temporaryDirectoryTemplate.withUnsafeBufferPointer { (ptr: UnsafeBufferPointer<CChar>) -> String in
-				return String.fromCString(ptr.baseAddress)!
-			}
-
-			let stdoutHandle = NSFileHandle(fileDescriptor: logFD, closeOnDealloc: true)
-			let temporaryURL = NSURL.fileURLWithPath(temporaryPath, isDirectory: false)!
-
-			let out: (NSFileHandle, NSURL?) = (stdoutHandle, temporaryURL)
```
Comment (robrix) [inline Source/carthage/Build.swift]: This is pretty nice.

File: Source/CarthageKit/FileSink.swift [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+	/// Sends the created sink and the URL to the temporary file.
+	public class func openTemporaryFile() -> ColdSignal<(FileSink, NSURL)> {
+		return ColdSignal.lazy {
+			var temporaryDirectoryTemplate: ContiguousArray<CChar> = NSTemporaryDirectory().stringByAppendingPathComponent("carthage-xcodebuild.XXXXXX.log").nulTerminatedUTF8.map { CChar($0) }
+			let logFD = temporaryDirectoryTemplate.withUnsafeMutableBufferPointer { (inout template: UnsafeMutableBufferPointer<CChar>) -> Int32 in
+				return mkstemps(template.baseAddress, 4)
+			}
+
+			if logFD < 0 {
+				return .error(NSError(domain: NSPOSIXErrorDomain, code: Int(errno), userInfo: nil))
```
Comment (robrix) [inline Source/CarthageKit/FileSink.swift]: Would it be useful to capture the path we attempted to use in `userInfo`?

File: Source/CarthageKit/FileSink.swift [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+			}
+
+			let temporaryPath = temporaryDirectoryTemplate.withUnsafeBufferPointer { (ptr: UnsafeBufferPointer<CChar>) -> String in
+				return String.fromCString(ptr.baseAddress)!
```
Comment (robrix) [inline Source/CarthageKit/FileSink.swift]: Can this be reduced to `temporaryDirectoryTemplate.withUnsafeBufferPointer(String.fromCString)!`?

File: Source/CarthageKitTests/FileSinkSpec.swift [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+			sink?.put(.Next(Box(foobarData)))
+			expect(NSString(contentsOfURL: URL, encoding: NSUTF8StringEncoding, error: nil)).to(equal("foobar\n"))
+
+			// Verify line buffering.
+			sink?.put(.Next(Box(fuzzbuzzData)))
+			expect(NSString(contentsOfURL: URL, encoding: NSUTF8StringEncoding, error: nil)).to(equal("foobar\n"))
+
+			// Verify output flushing.
+			sink?.put(.Completed)
+			expect(NSString(contentsOfURL: URL, encoding: NSUTF8StringEncoding, error: nil)).to(equal("foobar\nfuzzbuzz"))
```
Comment (robrix) [inline Source/CarthageKitTests/FileSinkSpec.swift]: :+1: These are great tests.

**Comment by robrix** [comment]
:+1:

File: Source/CarthageKit/FileSink.swift (hunk 4 above)
Comment (jspahrsummers) [inline Source/CarthageKit/FileSink.swift]: I don't think so, since it's just a template.

File: Source/CarthageKit/FileSink.swift (hunk 5 above)
Comment (jspahrsummers) [inline Source/CarthageKit/FileSink.swift]: Nope:

```
error: 'UnsafeBufferPointer<CChar>' is not a subtype of 'UnsafePointer<CChar>'
```

File: Source/CarthageKitTests/FileSinkSpec.swift (hunk 6 above)
Comment (jspahrsummers) [inline Source/CarthageKitTests/FileSinkSpec.swift]: Thanks!

**Comment by jspahrsummers** [comment]
@robrix I refactored `FileSink` a bit based on your feedback, primarily to remove the confusion about the error stuff.

In #368, I can restore the handling of `Event`, but explicitly mark it as `NoError`. Then, it can only be hooked up to pure logging streams that cannot error.

File: Source/CarthageKit/FileSink.swift (hunk 4 above)
Comment (robrix) [inline Source/CarthageKit/FileSink.swift]: :ok_hand:

File: Source/CarthageKit/FileSink.swift (hunk 5 above)
Comment (robrix) [inline Source/CarthageKit/FileSink.swift]: Thanks for checking :bow:

**Comment by robrix** [comment]
@jspahrsummers Okay. Did you want this to depend on #368? If not I’m :+1: to :shipit:

**Comment by jspahrsummers** [comment]
Nope, I'll fix it up within that PR. :ship:
