### PR TITLE
Don't pass Xcode errors through

### LINKED ISSUE #1626: Stop passing Xcode build warnings/errors through
When building fails, we pass the xcodebuild output through directly. This can be useful if you know what you're doing, but it seems to just confuse people in general—leading to bug reports, etc.

Instead, we should print something that directs people to the xcodebuild log.

### PR DESCRIPTION
**Pull request by mdiep**
Direct users to the xcodebuild log to help them self-diagnose errors.

Fixes #1626.

## Before
```
$ carthage update --no-use-binaries
*** Fetching Result
*** Checking out Result at "1.0.2"
*** xcodebuild output can be found in /var/folders/xj/sydx1wkd0p147x0k_7v667940000gn/T/carthage-xcodebuild.yIaqhL.log
*** Building scheme "Result-Mac" in Result.xcodeproj
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/mdiep/Downloads/tmp/Carthage/Checkouts/Result/Result.xcodeproj -scheme Result-Mac -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

## After
```
$ carthage-dev update --no-use-binaries
*** Fetching Result
*** Checking out Result at "1.0.2"
*** xcodebuild output can be found in /var/folders/xj/sydx1wkd0p147x0k_7v667940000gn/T/carthage-xcodebuild.NCkGIT.log
*** Building scheme "Result-Mac" in Result.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/mdiep/Downloads/tmp/Carthage/Checkouts/Result/Result.xcodeproj -scheme Result-Mac -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile.Please check the xcodebuild log for more details: /var/folders/xj/sydx1wkd0p147x0k_7v667940000gn/T/carthage-xcodebuild.NCkGIT.log
```

### CODE REVIEW

File: Source/carthage/Build.swift [hunk 1]
```diff
@@ -83,65 +83,49 @@ public struct BuildCommand: CommandType {
...
-					let grepTask: BuildSchemeProducer = Task("/usr/bin/grep", arguments: [ "--extended-regexp", "(warning|error|failed):" ]).launch(standardInput: stdoutProducer)
-						.on(next: { taskEvent in
-							switch taskEvent {
-							case let .StandardOutput(data):
-								stderrHandle.write(data)
+					buildProgress = buildProgress.filter { event in
+						switch event {
+						case .Launch, .Success:
+							return true
+						case .StandardError, .StandardOutput:
```
Comment (ikesyo) [inline Source/carthage/Build.swift]: [nit] I'd place `.StandardOutput` first as per the defined order.

File: Source/carthage/Build.swift [hunk 2]
```diff
@@ -83,65 +83,49 @@ public struct BuildCommand: CommandType {
...
+							return false
+						}
+					}
+				}
 
-							default:
-								break
+				return buildProgress
+					.flatMapError { error in
```
Comment (ikesyo) [inline Source/carthage/Build.swift]: `mapError` can be used here.

File: Source/CarthageKit/Xcode.swift [hunk 3]
```diff
@@ -687,6 +687,13 @@ public func buildInDirectory(directoryURL: URL, withOptions options: BuildOption
 				}
 
 				let buildProgress = buildScheme(scheme, withConfiguration: options.configuration, inProject: project, workingDirectoryURL: directoryURL, derivedDataPath: options.derivedDataPath, toolchain: options.toolchain, sdkFilter: wrappedSDKFilter)
+					.flatMapError { error -> SignalProducer<TaskEvent<URL>, CarthageError> in
```
Comment (ikesyo) [inline Source/CarthageKit/Xcode.swift]: `mapError` can be used here.
