### PR TITLE
Skip building for device SDKs on platforms that require bitcode when bitcode is disabled

### LINKED ISSUE #1268: Bitcode incompatibility for XCTest dependent frameworks on tvOS and watchOS
I'd like to discuss the possibility of better Carthage support for test frameworks on platforms that require bitcode.

* `carthage version`: 0.16
* `xcodebuild -version`: Xcode 7.3, Build version 7D175

## Situation

Apps built for a tvOS device are required to be built with bitcode. This causes problems for frameworks like Quick and Nimble that link to XCTest as it does not contain bitcode.

**Carthage Output**
```
$ carthage build --no-skip-current --platform tvos
*** xcodebuild output can be found in /var/folders/96/rcjvzrkn5lzfl0_krn8c151h0000gn/T/carthage-xcodebuild.TE6TlH.log
*** Building scheme "Quick-tvOS" in Quick.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Ld /Volumes/DerivedData/Quick-dshynvhuyaarriayewbsnvjxqrux/Build/Products/Release-appletvos/Quick.framework/Quick normal arm64
(1 failure)
ld: warning: Auto-Linking supplied '/Applications/Xcode7.3.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest', '/Applications/Xcode7.3.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE) or obtain an updated library from the vendor
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/phatblat/dev/ios/pods/Quick/Quick.xcworkspace -scheme Quick-tvOS -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Ld /Volumes/DerivedData/Quick-dshynvhuyaarriayewbsnvjxqrux/Build/Products/Release-appletvos/Quick.framework/Quick normal arm64
(1 failure)
```

Whenever we get [XCTest on watchOS](https://openradar.appspot.com/21760513) this will be an issue there as well.

These frameworks are not intended to be included with apps submitted to the app store. It would be nice if they could be included in device builds for local development testing. However, for platforms other than OS X, their primary environment is the various platform simulators.

## Affected Frameworks

- Quick/Nimble#213
- Quick/Quick#422

This is a total Catch-22 situation that Apple has put us in and I'm hoping that Carthage can make it a little less painful.

There are [workarounds](https://github.com/Quick/Nimble/issues/213#issuecomment-202496390) to this issue. Also, if Apple ever relaxes the bitcode requirement on tvOS and watchOS or adds bitcode to the XCTest framework, this will become a non-issue.

## Proposal

It is incredibly convenient for development that Carthage builds fat binaries with both device and simulator slices. However, when building a unit testing framework for a platform that requires bitcode this is a bit of a problem.

Since there is not presently a way to tell Carthage to only build for simulator architectures, what if the framework project's `ENABLE_BITCODE` setting of `NO` plus the combination of a platform that requires bitcode (`tvOS` and `watchOS`) were to disable generating the device architecture slices?

### Example tvOS Framework

- platform: `tvOS`
- `ENABLE_BITCODE`: `YES`
- generated slices: `x84_64`, `arm64`

### Example tvOS Test Framework

- platform: `tvOS`
- `ENABLE_BITCODE`: `NO`
- generated slices: `x84_64`

### Example watchOS Framework

- platform: `watchOS`
- `ENABLE_BITCODE`: `YES`
- generated slices: `i386`, `armv7k`

### Example watchOS Test Framework

- platform: `watchOS`
- `ENABLE_BITCODE`: `NO`
- generated slices: `i386`

Setting `ENABLE_BITCODE` to `NO` in most cases is an error on these platforms so I could see Carthage generating some sort of "are you sure?" warning. This approach seems simpler to me than something fancy like detecting that the framework links to XCTest or some other framework that isn't built with bitcode.

### PR DESCRIPTION
**Pull request by phatblat**
This is an attempt to get Carthage working for test frameworks like Quick and Nimble on the tvOS platform.

I'm new to ReactiveCocoa so I welcome any advice or suggestions on better ways to hook in this logic. Also, I'm not sure how to set up tests for this change as it looks like the current build tests in `XcodeSpec` all actually trigger real builds. Perhaps once I add `ENABLE_BITCODE=NO` to Quick and Nimble their projects could be used to test this.

Resolves #1268

### CODE REVIEW

File: Source/CarthageKit/Xcode.swift [hunk 1]
```diff
@@ -950,6 +950,25 @@ public func buildScheme(scheme: String, withConfiguration configuration: String,
 	}
 
 	return BuildSettings.SDKsForScheme(scheme, inProject: project)
+		.flatMap(.Concat) { sdk -> SignalProducer<(SDK, BuildSettings), CarthageError> in
+			var argsForLoading = buildArgs
+			argsForLoading.sdk = sdk
+
+			return SignalProducer(value: sdk)
+				.zipWith(BuildSettings.loadWithArguments(argsForLoading))
```
Comment (mdiep) [inline Source/CarthageKit/Xcode.swift]: Rather than creating a `SignalProducer` for `sdk` and using `zipWith`, you could just use `map`:

```swift
return BuildSettings
    .loadWithArguments(argsForLoading)
    .map { (sdk, $0) }
```

Comment (mdiep) [inline Source/CarthageKit/Xcode.swift]: Actually, I think you could move the `filter` inside here and get rid of the tuple  and the second `flatMap` altogether:

```swift
return BuildSettings
    .loadWithArguments(argsForLoading)
    .filter { settings in 
        return settings.bitcodeEnabled.value || ![.tvOS, .watchOS].contains(sdk)
    }
    .map { _ in sdk }
```

**Comment by mdiep** [comment]
Thanks for doing this! I left a suggest for how to simplify the code.

> Perhaps once I add ENABLE_BITCODE=NO to Quick and Nimble their projects could be used to test this.

That sounds right. 👍 

Have you tested this with Quick & Nimble? Do you have a fork that can be tested against? (It sounds like those projects don't currently have `ENABLE_BITCODE=NO`.)

File: Source/CarthageKit/Xcode.swift (hunk 1 above)
Comment (phatblat) [inline Source/CarthageKit/Xcode.swift]: Thank you! That's much simpler. I'll fix this up.

**Comment by phatblat** [comment]
Yes, I've tested this change against both Quick and Nimble with `ENABLE_BITCODE` disabled. Quick/Nimble#287 has been merged so it can be tested on Nimble's `master`. Quick has been having CI troubles making it hard to validate PRs, so the change is still in my [personal fork](https://github.com/phatblat/Quick/tree/ben/tvos3)

**Comment by phatblat** [comment]
This is ready for review. Below is example output from my testing of this change.

### Quick

```
carthage build --no-skip-current --platform tvos --verbose
*** Building scheme "Quick-tvOS" in Quick.xcworkspace
/usr/bin/xcrun xcodebuild -workspace /Users/phatblat/dev/ios/pods/Quick/Quick.xcworkspace -scheme Quick-tvOS -configuration Release -sdk appletvsimulator -destination platform=tvOS Simulator,id=5ABBC714-8605-44E7-9D0F-1E9B5C5F1AE3 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY =
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvsimulator9.2
…
    /usr/bin/touch -c /Users/phatblat/Library/Developer/Xcode/DerivedData/Quick-dshynvhuyaarriayewbsnvjxqrux/Build/Products/Release-appletvsimulator/Quick.framework

** BUILD SUCCEEDED **
```

### Nimble

```
carthage build --no-skip-current --platform tvos --verbose

*** Building scheme "Nimble-tvOS" in Nimble.xcodeproj
/usr/bin/xcrun xcodebuild -project /Users/phatblat/dev/ios/pods/Nimble/Nimble.xcodeproj -scheme Nimble-tvOS -configuration Release -sdk appletvsimulator -destination platform=tvOS Simulator,id=5ABBC714-8605-44E7-9D0F-1E9B5C5F1AE3 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY =
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvsimulator9.2
…
    /usr/bin/touch -c /Users/phatblat/Library/Developer/Xcode/DerivedData/Nimble-artuhuzwsatmpocyaaonwzeipcnw/Build/Products/Release-appletvsimulator/Nimble.framework

** BUILD SUCCEEDED **
```

**Comment by phatblat** [comment]
Some spaces snuck into my copy/pasta 🍜😳

**Comment by phatblat** [comment]
Looks like `-[CarthageKitTests.XcodeSpec should_build_for_all_platforms]` is failing. A second `Mac OS X` sdk is sneaking through in the ReactiveCocoaLayout Mac build.

```
fatal error: Could not find simulator SDK in [Mac OS X, Mac OS X]: file /Users/phatblat/dev/xcode/Carthage/Source/CarthageKit/Xcode.swift, line 1009
```

**Comment by phatblat** [comment]
I'm not sure why but `BuildSettings.loadWithArguments` was _sometimes_ loading 2 or 4 copies of `settings` for a given `sdk` and then the assertion would catch the duplicates before actually attempting a build. It was a bit random and sometimes would fail on Archimedes and sometimes on ReactiveCocoa.

I've added logic to filter out any duplicate `sdk` values, but there may be a better way to do this that I'm not seeing.

File: Source/CarthageKit/Xcode.swift [hunk 2]
```diff
@@ -950,13 +950,29 @@ public func buildScheme(scheme: String, withConfiguration configuration: String,
...
+				.loadWithArguments(argsForLoading)
+				.filter { settings in
+					// Filter out SDKs that require bitcode when bitcode is disabled in
+					// project settings. This is necessary for testing frameworks, which
+					// must add a User-Defined setting of ENABLE_BITCODE=NO.
+					return settings.bitcodeEnabled.value == true || ![.tvOS, .watchOS].contains(sdk)
+				}
+				.map { _ in sdk }
+		}
 		.reduce([:]) { (sdksByPlatform: [Platform: [SDK]], sdk: SDK) in
```
Comment (mdiep) [inline Source/CarthageKit/Xcode.swift]: Could we maybe change `sdksByPlatform` to `[Platform: Set<SDK>]` to filter out duplicates?

Comment (phatblat) [inline Source/CarthageKit/Xcode.swift]: I was thinking the same thing

**Comment by phatblat** [comment]
This is ready for review

**Comment by mdiep** [comment]
✨

**Comment by phatblat** [comment]
🎉
