### PR TITLE
Ensure input files to copy-frameworks are unique

### LINKED ISSUE #1901: Regression in 0.21: copy-frameworks fails with various filesystem errors
#### Summary

After upgrading to 0.21 (using `brew upgrade carthage`), I started to see various filesystem errors while `copy-frameworks` is run in a Build Phase.

I tried doing `bootstrap`, `update` (both with and without `--cache-builds`), but the result is still the same – the script stops on a particular framework ([Kingfisher 3.6.2](https://github.com/onevcat/Kingfisher/releases/tag/3.6.2)) with various filesystem errors, which tend to differ between <kbd>⌘B</kbd> hits.

#### Examples of errors

```none
Failed to write to /<redacted>/Library/Developer/Xcode/DerivedData/<redacted>-hfdzmzweexlzswgvsyoqupohotyp/Build/Products/<redacted>-iphonesimulator/<redacted>.app/Frameworks/Kingfisher.framework: Error Domain=NSCocoaErrorDomain Code=516 "“Kingfisher.h” couldn’t be copied to “Headers” because an item with the same name already exists." UserInfo={NSSourceFilePathErrorKey=/<redacted>/Carthage/Build/iOS/Kingfisher.framework/Headers/Kingfisher.h, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/<redacted>/Library/Developer/Xcode/DerivedData/<redacted>-hfdzmzweexlzswgvsyoqupohotyp/Build/Products/<redacted>-iphonesimulator/<redacted>.app/Frameworks/Kingfisher.framework/Headers/Kingfisher.h, NSFilePath=/<redacted>/Carthage/Build/iOS/Kingfisher.framework/Headers/Kingfisher.h, NSUnderlyingError=0x7f8c7187f5f0 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}
```

```none
Failed to write to /<redacted>/Library/Developer/Xcode/DerivedData/<redacted>-hfdzmzweexlzswgvsyoqupohotyp/Build/Products/<redacted>-iphonesimulator/<redacted>.app/Frameworks/Kingfisher.framework: Error Domain=NSCocoaErrorDomain Code=516 "“Modules” couldn’t be copied to “Kingfisher.framework” because an item with the same name already exists." UserInfo={NSSourceFilePathErrorKey=/<redacted>/Carthage/Build/iOS/Kingfisher.framework/Modules, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/<redacted>/Library/Developer/Xcode/DerivedData/FitnessApp-hfdzmzweexlzswgvsyoqupohotyp/Build/Products/<redacted>-iphonesimulator/<redacted>.app/Frameworks/Kingfisher.framework/Modules, NSFilePath=/<redacted>/Carthage/Build/iOS/Kingfisher.framework/Modules, NSUnderlyingError=0x7fe5a735ed30 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}
```

#### Regression?

I suspect it to be a regression because switching back to 0.20.1 (using `brew switch carthage 0.20.1`) and rebuilding the project (with or without doing `bootstrap` again), `copy-frameworks` works as expected.

#### Reproducible sample code

I will try to attach some reproducible project tomorrow (I just wanted to report the issue itself as soon as possible).

---

#### Environment

`carthage version`: 0.21
`xcodebuild -version`: 8.3.2 (8E2002)

`--no-build`: no
`--no-use-binaries`: no
`--use-submodules`: no
`--cache-builds`: yes and no

### PR DESCRIPTION
**Pull request by erichoracek**
Duplicated input files can cause failures. Fixes #1901.

### CODE REVIEW

File: Source/carthage/CopyFrameworks.swift [hunk 1]
```diff
@@ -165,7 +165,8 @@ private func inputFiles() -> SignalProducer<String, CarthageError> {
 				return SignalProducer(result: getEnvironmentVariable("SCRIPT_INPUT_FILE_\(index)"))
 			}
 
-			return SignalProducer<SignalProducer<String, CarthageError>, CarthageError>(variables)
-				.flatten(.concat)
+			return SignalProducer.zip(variables)
+				.map { Set($0) }
+				.flatMap(.concat) { SignalProducer<String, CarthageError>($0) }
```
Comment (mdiep) [inline Source/carthage/CopyFrameworks.swift]: Would you mind cleaning this up a bit and using `uniqueValues`? Something like this:

```swift
return SignalProducer(result: count)
    .flatMap(.merge) { return .init(values: 0..<$0) }
    .map { getEnvironmentVariable("SCRIPT_INPUT_FILE_\($0)" }
    .uniqueValues()
```

Comment (erichoracek) [inline Source/carthage/CopyFrameworks.swift]: Good call! I've updated the PR.

**Comment by mdiep** [comment]
Thanks for taking care of this! 🤘
