### PR TITLE
Use checked out cartfile

### LINKED ISSUE #2034: Unexpected fetch on build command
* `carthage version`: 0.23.0
* `xcodebuild -version`: 8.3.3
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no
* Are you using `--cache-builds`? yes

We are committing the checkout folder with our app to use it with CI. The CI builds with 

`build --cache-builds --platform iOS`

Unexpected: Carthage performs a fetch for some dependencies before the build. That breaks the CI for dependencies that need credentials - since we don't supply them on CI at the moment.

We would not expect `build` to perform a fetch. 

Is the fetch expected - and why? How could we ensure that build does not perform a fetch?

### PR DESCRIPTION
**Pull request by BobElDevil**
Fixes #2034 

This attempts to read the Cartfile from the current source checkout first (except during 'update' resolution) before falling back to the current git cache read/fetch.

### CODE REVIEW

File: Source/CarthageKit/Project.swift [hunk 1]
```diff
@@ -745,10 +771,13 @@ public final class Project { // swiftlint:disable:this type_body_length
 			}
 
 		return loadResolvedCartfile()
-			.flatMap(.merge) { resolvedCartfile in
-				return self
-					.buildOrderForResolvedCartfile(resolvedCartfile, dependenciesToInclude: dependenciesToCheckout)
-					.collect()
+			.map { resolvedCartfile -> [(Dependency, PinnedVersion)] in
+				let dependencies = resolvedCartfile.dependencies
+				return dependencies.keys
```
Comment (BobElDevil) [inline Source/CarthageKit/Project.swift]: Since we were already doing checkouts concurrently, I realized we were wasting cycles figuring out the build order, and we really just want to checkout anything we find in the list.

File: Source/CarthageKit/Project.swift [hunk 2]
```diff
@@ -314,17 +304,53 @@ public final class Project { // swiftlint:disable:this type_body_length
...
-			return self.cloneOrFetchDependency(dependency, commitish: revision)
+			let cartfileFetch: SignalProducer<Cartfile, CarthageError> = self.cloneOrFetchDependency(dependency, commitish: revision)
 				.flatMap(.concat) { repositoryURL in
 					return contentsOfFileInRepository(repositoryURL, Constants.Project.cartfilePath, revision: revision)
 				}
 				.flatMapError { _ in .empty }
 				.attemptMap(Cartfile.from(string:))
+
+			let cartfileSource: SignalProducer<Cartfile, CarthageError>
+			if tryCheckoutDirectory {
```
Comment (ikesyo) [inline Source/CarthageKit/Project.swift]: I'm not confident that if this is really correct / safe––looks like the revision is not taken into account. Please correct me if I am wrong.

File: Source/CarthageKit/Project.swift [hunk 3]
```diff
@@ -314,17 +304,53 @@ public final class Project { // swiftlint:disable:this type_body_length
...
+				let dependencyURL = self.directoryURL.appendingPathComponent(dependency.relativePath)
+				cartfileSource = SignalProducer<Bool, NoError> {
+					var isDirectory: ObjCBool = false
+					return FileManager.default.fileExists(atPath: dependencyURL.path, isDirectory: &isDirectory) && isDirectory.boolValue
```
Comment (ikesyo) [inline Source/CarthageKit/Project.swift]: Wrong indentations.

File: Source/CarthageKit/Project.swift (hunk 2 above)
Comment (BobElDevil) [inline Source/CarthageKit/Project.swift]: It's not taking the revision explicitly into account. However this is the same amount of verification that any step of the build phase takes. Right now we check the Cartfile.resolved for build order but build whatever happens to be sitting in  the checkout folder. So if we're assuming that we're building the right revision at that point, then it is no worse to also read the Cartfile from there.

File: Source/CarthageKit/Project.swift [hunk 4]
```diff
@@ -745,10 +771,13 @@ public final class Project { // swiftlint:disable:this type_body_length
...
-			.flatMap(.merge) { resolvedCartfile in
-				return self
-					.buildOrderForResolvedCartfile(resolvedCartfile, dependenciesToInclude: dependenciesToCheckout)
-					.collect()
+			.map { resolvedCartfile -> [(Dependency, PinnedVersion)] in
+				let dependencies = resolvedCartfile.dependencies
+				return dependencies.keys
+					.filter { dependenciesToCheckout?.contains($0.name) ?? true }
+					.map { key in
+						(key, dependencies[key]!)
```
Comment (mdiep) [inline Source/CarthageKit/Project.swift]: I think you could get rid of this `map` if you get rid of the `keys` above?

```swift
return resolvedCartfile
    .dependencies
    .filter { dependenciesToCheckout?.contains($0.name) ?? true }
```

Comment (BobElDevil) [inline Source/CarthageKit/Project.swift]: Well dependencies is a dictionary, and we want to process each item, but that can be worked down a level when it's zipped with the submodule dictionary, rather than doing it here to force it into an array.

File: Source/CarthageKit/Project.swift (hunk 3 above)
Comment (BobElDevil) [inline Source/CarthageKit/Project.swift]: Will fix, got thrown off by where the braces go for an init with closure + additional operations, but found another example to base it off of

File: Source/CarthageKit/Project.swift [hunk 5]
```diff
@@ -314,17 +304,53 @@ public final class Project { // swiftlint:disable:this type_body_length
...
+				cartfileSource = SignalProducer<Bool, NoError> {
+					var isDirectory: ObjCBool = false
+					return FileManager.default.fileExists(atPath: dependencyURL.path, isDirectory: &isDirectory) && isDirectory.boolValue
+				}
+				.flatMap(.concat) { directoryExists -> SignalProducer<Cartfile, CarthageError> in
+					if directoryExists {
+						return SignalProducer(result: Cartfile.from(file: dependencyURL.appendingPathComponent(Constants.Project.cartfilePath)))
+							.flatMapError { _ in .empty }
+					} else {
+						return cartfileFetch
```
Comment (mdiep) [inline Source/CarthageKit/Project.swift]: I'm not sure we should fetch the `Cartfile` here. If the checked out version is going to be the source of truth, then we should probably make it the source of truth.

What do you think?

Comment (BobElDevil) [inline Source/CarthageKit/Project.swift]: This covers the case where the checkout isn't there, like when we have a binary release. 

If we resolved #1466 (and solved the blocking issue that we build everything in the folder without verifying there were binary releases), then we wouldn't need this backup behavior anymore.
