### PR TITLE
Remove explicit unwrap of optional when looking for framework source

### LINKED ISSUE #404: unexpectedly found nil while unwrapping an Optional value
I have added [XCGLogger](https://github.com/DaveWoodCom/XCGLogger) (the swift 1.2 branch) to my Cartfile.
Carthage builds fine.
I have added the built framework to my target and added the framework to my "copy-frameworks" step according to carthage documentation.
When I build my target I get the following error:
```
line 2: 47908 Illegal instruction: 4  /usr/local/bin/carthage copy-frameworks
fatal error: unexpectedly found nil while unwrapping an Optional value
```
I have also reported this issue to the XCGLogger project since I don't know the cause yet.

### PR DESCRIPTION
**Pull request by eliperkins**
(Hopefully) Fixes #404

### CODE REVIEW

File: Source/carthage/CopyFrameworks.swift [hunk 1]
```diff
@@ -24,11 +24,11 @@ public struct CopyFrameworksCommand: CommandType {
 				|> flatMap(.Concat) { frameworkPath -> SignalProducer<(), CarthageError> in
 					let frameworkName = frameworkPath.lastPathComponent
 
-					let source = NSURL(fileURLWithPath: frameworkPath, isDirectory: true)!
+					let source = Result(NSURL(fileURLWithPath: frameworkPath, isDirectory: true), failWith: CarthageError.InvalidArgument(description: "Could not find framework \"\(frameworkName)\" at path \(frameworkPath). Ensure that the given path is approriately entered. Ensure that your \"Input Files\" have been entered correctly."))
```
Comment (mdiep) [inline Source/carthage/CopyFrameworks.swift]: I would combine the "Ensure that" sentences. ("…entered and that your…").

Also, there's a typo in _appropriately_.

**Comment by mdiep** [comment]
This looks good, but unfortunately it conflicts with `master` now. :weary:

If you wouldn't mind updating it, I'd love to merge it! Sorry for the delay!

File: Source/carthage/CopyFrameworks.swift [hunk 2]
```diff
@@ -24,11 +24,11 @@ public struct CopyFrameworksCommand: CommandType {
 				|> flatMap(.Concat) { frameworkPath -> SignalProducer<(), CarthageError> in
 					let frameworkName = frameworkPath.lastPathComponent
 
-					let source = NSURL(fileURLWithPath: frameworkPath, isDirectory: true)!
+					let source = Result(NSURL(fileURLWithPath: frameworkPath, isDirectory: true), failWith: CarthageError.InvalidArgument(description: "Could not find framework \"\(frameworkName)\" at path \(frameworkPath). Ensure that the given path is appropriately entered and that your \"Input Files\" have been entered correctly."))
 					let target = frameworksFolder().map { $0.URLByAppendingPathComponent(frameworkName, isDirectory: true) }
 
-					return SignalProducer(result: target &&& validArchitectures())
-						|> flatMap(.Merge) { (target, validArchitectures) -> SignalProducer<(), CarthageError> in
+					return combineLatest(SignalProducer(result: source), SignalProducer(result: target), SignalProducer(result: validArchitectures()))
```
Comment (eliperkins) [inline Source/carthage/CopyFrameworks.swift]: After checking out antitypical/Result#47 and #547, I swapped this back to a `combineLatest` to handle the next value coming along. Using `&&&` created a tuple within a tuple instead of a tuple with three values. 

Not sure if this is best! @robrix @ikesyo

**Comment by eliperkins** [comment]
:racehorse:

**Comment by mdiep** [comment]
Looks great—thanks! :sparkles:
