### PR TITLE
Fix fetching a local repository with relative path

### LINKED ISSUE #968: Carthage doesn't appear to "see" latest commit of local repository specified with a relative path
This is kind of an obscure corner case. I have a `Cartfile` that specifies a dependency on a local repo like this:

```
git "../ISUtils" 
```

If I run `carthage update` I get

```
$ carthage update
*** Fetching ISUtils
*** Checking out ISUtils at "1.0.0"
```

I can change the Cartfile to specify the same repo using an absolute path

```
git "file:///Users/bryan/Documents/ISUtils"
```

Now if I run `carthage update` I get

```
$ carthage update
*** Fetching ISUtils
*** Checking out ISUtils at "1.0.1"
```

The second checkout is correct, the latest commit is tagged "1.0.1". The commit before that ("`HEAD~1`") is tagged as "1.0.0".

### PR DESCRIPTION
**Pull request by ikesyo**
Specifically for the case of `../some-repo`. Formerly `cloneOrFetch` fetches a repository itself as its remote in that case because of the given `GitURL` of `../some-repo`.

In short, running the following command within `~/Library/Caches/org.carthage.CarthageKit/dependencies/some-repo` is the problem.

```bash
# ../some-repo is pointing to the repository itself
/usr/bin/env git fetch --prune --quiet ../some-repo refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/*
```

We should be able to use the `origin` remote instead of `../some-repo` here.

Fixes #968.

### CODE REVIEW

File: Source/CarthageKit/Project.swift [hunk 1]
```diff
@@ -1208,13 +1208,18 @@ public func cloneOrFetch(
...
 
 							return SignalProducer(value: (.fetching(dependency), repositoryURL))
 								.concat(
-									fetchRepository(repositoryURL, remoteURL: remoteURL, refspec: "+refs/heads/*:refs/heads/*")
+									// Don't need to pass `remoteURL` here since the repository should have 
+									// the `origin` remote.
+									//
+									// See https://github.com/Carthage/Carthage/issues/968
+									// and https://github.com/Carthage/Carthage/pull/2125.
+									fetchRepository(repositoryURL, refspec: "+refs/heads/*:refs/heads/*")
```
Comment (BobElDevil) [inline Source/CarthageKit/Project.swift]: The only other place we use this function is when we fetch submodules, which we have also set up with the 'origin' remote. It might it make sense to just remove the remoteURL argument and fix up the submodule usage as well.

Comment (ikesyo) [inline Source/CarthageKit/Project.swift]: Thanks @BobElDevil, that makes sense. ✨

**Comment by mdiep** [comment]
Nicely done. :clap

**Comment by sukeshmlr** [comment]
Thanks a lot. This is a much needed fix.

**Comment by dunqi** [comment]
You have to delete the dependency in:
 /Users/username/Library/Caches/org.carthage.CarthageKit/dependencies/nameofframework

And then checkout again - works for me
